### ISSUE TITLE
Unable to reproduce CollectMineralShards result

### ISSUE THREAD

**Issue by vwxyzjn** [pekaalto/sc2aibot#3]
Hi,

I was trying to reproduce the CollectMineralShards result you posted here: 

![image](https://user-images.githubusercontent.com/5555347/33227848-34058ea2-d17b-11e7-946a-d48eac7a2caa.png)

by running 

```
python run_agent.py --map_name CollectMineralShards --model_name my_mineral_shards_model
```

However, after 60k steps, the rewards still remain around 25

![capture](https://user-images.githubusercontent.com/5555347/33227857-5ceb0270-d17b-11e7-8ff5-f9b6f59dbc51.PNG)

I did not use the flag ``--n_envs 32``. Would that be the cause of this irreproducibility?

Thank you.

**Comment by pekaalto** [comment]
Hi, actually the x-axis in this chart is number or episodes. In your screenshot can see that you have only 2100 episodes so far. So it's long way to go.

Other notes:
-The training is probably more robust with multiple environments even if run same number of episodes.
-There is lot of randomness involved in the learning process. You will get different training graph each run.

**Comment by vwxyzjn** [comment]
I see. Thank you!
