### ISSUE TITLE
I have a question as following 

### ISSUE THREAD

**Issue by miqianmimi** [pekaalto/sc2aibot#5]
Where is the test.py which function is to test the existing model after training . Because i can't find any test python in the Readme

**Comment by pekaalto** [comment]
Hi,
I am not sure what testing script you are referring to. You can simply see existing agent play without training by specifying `--notraining` flag.
Example: `python run_agent.py --map_name MoveToBeacon --model_name my_beacon_model --n_envs 1 --notraining`

**Comment by miqianmimi** [comment]
thank u so much

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
